# Dockerfile.frontend.prd
FROM node:20-alpine AS builder
WORKDIR /app
COPY ./frontend_docker_prd/ .
RUN npm install
RUN npm run build

# ↓ 本番用 Nginx イメージへコピー
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./frontend_docker_prd/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
